# Generated by Django 6.0.6 on 2026-06-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('time', models.TimeField(verbose_name='Soat')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Band qilingan')),
            ],
            options={
                'verbose_name': 'Vaqt katakchasi',
                'verbose_name_plural': 'Vaqt katakchalari',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='Bemor ismi')),
                ('patient_phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('complaint', models.TextField(blank=True, null=True, verbose_name='Shikoyati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.timeslot', verbose_name='Tanlangan vaqt')),
            ],
            options={
                'verbose_name': 'Navbat',
                'verbose_name_plural': 'Navbatlar',
            },
        ),
    ]
