# Generated by Django 6.0.6 on 2026-06-10 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Qabul navbati', 'verbose_name_plural': 'Fuqarolar qabuli (Navbatlar)'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Vaqt Sloti', 'verbose_name_plural': 'Qabul Vaqt Slotlari'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='complaint',
            field=models.TextField(blank=True, default=1, verbose_name='Murojaat mazmuni'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(max_length=100, verbose_name='Fuqaro F.I.O'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.timeslot', verbose_name='Vaqt sloti'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='date',
            field=models.DateField(verbose_name='Qabul kuni'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Band qilinganmi'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(verbose_name='Qabul vaqti'),
        ),
    ]
