# Generated by Django 6.0.6 on 2026-06-11 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_alter_timeslot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Fuqaro arizasi', 'verbose_name_plural': 'Kelib tushgan murojaatlar (Navbatlar)'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Qabul vaqti', 'verbose_name_plural': 'Hokimiyat qabul vaqtlari'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='complaint',
            field=models.TextField(blank=True, verbose_name='Murojaat/Muammo mazmuni'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan sana'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(max_length=20, verbose_name='Fuqaro telefon raqami'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.timeslot', verbose_name='Belgilangan vaqt sloti'),
        ),
    ]
